// Generated by gencpp from file turtlebot3_deliver_service/AvailableItemList.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_DELIVER_SERVICE_MESSAGE_AVAILABLEITEMLIST_H
#define TURTLEBOT3_DELIVER_SERVICE_MESSAGE_AVAILABLEITEMLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_deliver_service
{
template <class ContainerAllocator>
struct AvailableItemList_
{
  typedef AvailableItemList_<ContainerAllocator> Type;

  AvailableItemList_()
    : item_number(0)
    , is_item_available(false)  {
    }
  AvailableItemList_(const ContainerAllocator& _alloc)
    : item_number(0)
    , is_item_available(false)  {
  (void)_alloc;
    }



   typedef uint32_t _item_number_type;
  _item_number_type item_number;

   typedef uint8_t _is_item_available_type;
  _is_item_available_type is_item_available;





  typedef boost::shared_ptr< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> const> ConstPtr;

}; // struct AvailableItemList_

typedef ::turtlebot3_deliver_service::AvailableItemList_<std::allocator<void> > AvailableItemList;

typedef boost::shared_ptr< ::turtlebot3_deliver_service::AvailableItemList > AvailableItemListPtr;
typedef boost::shared_ptr< ::turtlebot3_deliver_service::AvailableItemList const> AvailableItemListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator1> & lhs, const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator2> & rhs)
{
  return lhs.item_number == rhs.item_number &&
    lhs.is_item_available == rhs.is_item_available;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator1> & lhs, const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_deliver_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c8abaae09f0bffda0bd8946d2c8b728";
  }

  static const char* value(const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c8abaae09f0bffdULL;
  static const uint64_t static_value2 = 0xa0bd8946d2c8b728ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_deliver_service/AvailableItemList";
  }

  static const char* value(const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 item_number \n"
"bool is_item_available\n"
;
  }

  static const char* value(const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.item_number);
      stream.next(m.is_item_available);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AvailableItemList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_deliver_service::AvailableItemList_<ContainerAllocator>& v)
  {
    s << indent << "item_number: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.item_number);
    s << indent << "is_item_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_item_available);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_DELIVER_SERVICE_MESSAGE_AVAILABLEITEMLIST_H
