// Generated by gencpp from file turtlebot3_deliver_service/InitTurtlebotPoseRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSEREQUEST_H
#define TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovarianceStamped.h>

namespace turtlebot3_deliver_service
{
template <class ContainerAllocator>
struct InitTurtlebotPoseRequest_
{
  typedef InitTurtlebotPoseRequest_<ContainerAllocator> Type;

  InitTurtlebotPoseRequest_()
    : poseWithCovarianceStamped()  {
    }
  InitTurtlebotPoseRequest_(const ContainerAllocator& _alloc)
    : poseWithCovarianceStamped(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator>  _poseWithCovarianceStamped_type;
  _poseWithCovarianceStamped_type poseWithCovarianceStamped;





  typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitTurtlebotPoseRequest_

typedef ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<std::allocator<void> > InitTurtlebotPoseRequest;

typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest > InitTurtlebotPoseRequestPtr;
typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest const> InitTurtlebotPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.poseWithCovarianceStamped == rhs.poseWithCovarianceStamped;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_deliver_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd1774f5f4457d898f2470c31d60fe55";
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd1774f5f4457d89ULL;
  static const uint64_t static_value2 = 0x8f2470c31d60fe55ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_deliver_service/InitTurtlebotPoseRequest";
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseWithCovarianceStamped poseWithCovarianceStamped\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovarianceStamped\n"
"# This expresses an estimated pose with a reference coordinate frame and timestamp\n"
"\n"
"Header header\n"
"PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poseWithCovarianceStamped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitTurtlebotPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "poseWithCovarianceStamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.poseWithCovarianceStamped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSEREQUEST_H
