// Generated by gencpp from file turtlebot3_deliver_service/InitTurtlebotPoseResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSERESPONSE_H
#define TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_deliver_service
{
template <class ContainerAllocator>
struct InitTurtlebotPoseResponse_
{
  typedef InitTurtlebotPoseResponse_<ContainerAllocator> Type;

  InitTurtlebotPoseResponse_()
    {
    }
  InitTurtlebotPoseResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitTurtlebotPoseResponse_

typedef ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<std::allocator<void> > InitTurtlebotPoseResponse;

typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse > InitTurtlebotPoseResponsePtr;
typedef boost::shared_ptr< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse const> InitTurtlebotPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace turtlebot3_deliver_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_deliver_service/InitTurtlebotPoseResponse";
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitTurtlebotPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::turtlebot3_deliver_service::InitTurtlebotPoseResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSERESPONSE_H
