// Generated by gencpp from file turtlebot3_deliver_service/InitTurtlebotPose.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSE_H
#define TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSE_H

#include <ros/service_traits.h>


#include <turtlebot3_deliver_service/InitTurtlebotPoseRequest.h>
#include <turtlebot3_deliver_service/InitTurtlebotPoseResponse.h>


namespace turtlebot3_deliver_service
{

struct InitTurtlebotPose
{

typedef InitTurtlebotPoseRequest Request;
typedef InitTurtlebotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitTurtlebotPose
} // namespace turtlebot3_deliver_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPose > {
  static const char* value()
  {
    return "dd1774f5f4457d898f2470c31d60fe55";
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPose&) { return value(); }
};

template<>
struct DataType< ::turtlebot3_deliver_service::InitTurtlebotPose > {
  static const char* value()
  {
    return "turtlebot3_deliver_service/InitTurtlebotPose";
  }

  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPose&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest> should match
// service_traits::MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPose >
template<>
struct MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPose >::value();
  }
  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest> should match
// service_traits::DataType< ::turtlebot3_deliver_service::InitTurtlebotPose >
template<>
struct DataType< ::turtlebot3_deliver_service::InitTurtlebotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_deliver_service::InitTurtlebotPose >::value();
  }
  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse> should match
// service_traits::MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPose >
template<>
struct MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_deliver_service::InitTurtlebotPose >::value();
  }
  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse> should match
// service_traits::DataType< ::turtlebot3_deliver_service::InitTurtlebotPose >
template<>
struct DataType< ::turtlebot3_deliver_service::InitTurtlebotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_deliver_service::InitTurtlebotPose >::value();
  }
  static const char* value(const ::turtlebot3_deliver_service::InitTurtlebotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT3_DELIVER_SERVICE_MESSAGE_INITTURTLEBOTPOSE_H
