// Generated by gencpp from file turtlebot3_deliver_service/PadOrder.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_DELIVER_SERVICE_MESSAGE_PADORDER_H
#define TURTLEBOT3_DELIVER_SERVICE_MESSAGE_PADORDER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_deliver_service
{
template <class ContainerAllocator>
struct PadOrder_
{
  typedef PadOrder_<ContainerAllocator> Type;

  PadOrder_()
    : pad_number(0)
    , item_number(0)  {
    }
  PadOrder_(const ContainerAllocator& _alloc)
    : pad_number(0)
    , item_number(0)  {
  (void)_alloc;
    }



   typedef uint32_t _pad_number_type;
  _pad_number_type pad_number;

   typedef uint32_t _item_number_type;
  _item_number_type item_number;





  typedef boost::shared_ptr< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> const> ConstPtr;

}; // struct PadOrder_

typedef ::turtlebot3_deliver_service::PadOrder_<std::allocator<void> > PadOrder;

typedef boost::shared_ptr< ::turtlebot3_deliver_service::PadOrder > PadOrderPtr;
typedef boost::shared_ptr< ::turtlebot3_deliver_service::PadOrder const> PadOrderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator1> & lhs, const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator2> & rhs)
{
  return lhs.pad_number == rhs.pad_number &&
    lhs.item_number == rhs.item_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator1> & lhs, const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_deliver_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f312fcf0d154bf3751121cfb69eca080";
  }

  static const char* value(const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf312fcf0d154bf37ULL;
  static const uint64_t static_value2 = 0x51121cfb69eca080ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_deliver_service/PadOrder";
  }

  static const char* value(const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 pad_number\n"
"uint32 item_number\n"
;
  }

  static const char* value(const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pad_number);
      stream.next(m.item_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PadOrder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_deliver_service::PadOrder_<ContainerAllocator>& v)
  {
    s << indent << "pad_number: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pad_number);
    s << indent << "item_number: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.item_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_DELIVER_SERVICE_MESSAGE_PADORDER_H
